kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: myspringbootapp
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      containers:
        - name: myspringbootapp
          image: ravihebbal/valaxy2-demo-java1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
